// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Admin.Controllers {
    [CompilerGenerated]
    public partial class UserController {
        public UserController() { }

        protected UserController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, Actions.Edit);
        }
        [NonAction]
        public System.Web.Mvc.JsonResult Search() {
            return new T4MVC_JsonResult(Area, Name, Actions.Search);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Assume() {
            return new T4MVC_ActionResult(Area, Name, Actions.Assume);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Reset() {
            return new T4MVC_ActionResult(Area, Name, Actions.Reset);
        }

        public readonly string Area = "Admin";
        public readonly string Name = "User";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Edit = "Edit";
            public readonly string Search = "Search";
            public readonly string Assume = "Assume";
            public readonly string Reset = "Reset";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Edit = "~/Areas/Admin/Views/User/Edit.spark";
            public readonly string Index = "~/Areas/Admin/Views/User/Index.spark";
            public readonly string UserCreateModel = "~/Areas/Admin/Views/User/UserCreateModel.spark";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string LoginIncrements = "~/Areas/Admin/Views/User/DisplayTemplates/LoginIncrements.spark";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string UserState = "~/Areas/Admin/Views/User/EditorTemplates/UserState.spark";
            }
        }
    }

    [CompilerGenerated]
    class T4MVC_UserController: Ascend.Web.Areas.Admin.Controllers.UserController {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(Ascend.Web.Areas.Admin.Controllers.UserCreateModel u) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("u", u);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id, Ascend.Web.Areas.Admin.Controllers.UserEditModel u) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("u", u);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Search(string term) {
            var callInfo = new T4MVC_JsonResult(Area, Name, Actions.Search);
            callInfo.RouteValues.Add("term", term);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Assume(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Assume);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Reset(string id, bool? sendEmail) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Reset);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("sendEmail", sendEmail);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
