// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Admin.Controllers {
    [CompilerGenerated]
    public partial class ProductController {
        public ProductController() { }

        protected ProductController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, Actions.Index);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult RenameCategory() {
            return new T4MVC_ActionResult(Area, Name, Actions.RenameCategory);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Enable() {
            return new T4MVC_ActionResult(Area, Name, Actions.Enable);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Categorize() {
            return new T4MVC_ActionResult(Area, Name, Actions.Categorize);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Tag() {
            return new T4MVC_ActionResult(Area, Name, Actions.Tag);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, Actions.Edit);
        }

        public readonly string Area = "Admin";
        public readonly string Name = "Product";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string RenameCategory = "RenameCategory";
            public readonly string ClearImages = "ClearImages";
            public readonly string RefreshImages = "RefreshImages";
            public readonly string Enable = "Enable";
            public readonly string Categorize = "Categorize";
            public readonly string Tag = "Tag";
            public readonly string Edit = "Edit";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string _Filter = "~/Areas/Admin/Views/Product/_Filter.spark";
            public readonly string Edit = "~/Areas/Admin/Views/Product/Edit.spark";
            public readonly string Index = "~/Areas/Admin/Views/Product/Index.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_ProductController: Ascend.Web.Areas.Admin.Controllers.ProductController {
        public T4MVC_ProductController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(Ascend.Web.Areas.Admin.Controllers.ProductFilterModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RenameCategory(string from, string to) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.RenameCategory);
            callInfo.RouteValues.Add("from", from);
            callInfo.RouteValues.Add("to", to);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ClearImages() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.ClearImages);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RefreshImages() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.RefreshImages);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Enable(string[] ids, bool? enable) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Enable);
            callInfo.RouteValues.Add("ids", ids);
            callInfo.RouteValues.Add("enable", enable);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Categorize(string[] ids, string category) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Categorize);
            callInfo.RouteValues.Add("ids", ids);
            callInfo.RouteValues.Add("category", category);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Tag(string[] ids, string[] tag) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Tag);
            callInfo.RouteValues.Add("ids", ids);
            callInfo.RouteValues.Add("tag", tag);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id, Ascend.Web.Areas.Admin.Controllers.ProductEditModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
