// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Admin.Controllers {
    [CompilerGenerated]
    public partial class ImportController {
        public ImportController() { }

        protected ImportController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, Actions.Edit);
        }

        public readonly string Area = "Admin";
        public readonly string Name = "Import";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Edit = "Edit";
            public readonly string Review = "Review";
            public readonly string Events = "Events";
            public readonly string Reset = "Reset";
            public readonly string Randomizer = "Randomizer";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Edit = "~/Areas/Admin/Views/Import/Edit.spark";
            public readonly string Events = "~/Areas/Admin/Views/Import/Events.spark";
            public readonly string ImportCreateModel = "~/Areas/Admin/Views/Import/ImportCreateModel.spark";
            public readonly string Index = "~/Areas/Admin/Views/Import/Index.spark";
            public readonly string Randomizer = "~/Areas/Admin/Views/Import/Randomizer.spark";
            public readonly string Reset = "~/Areas/Admin/Views/Import/Reset.spark";
            public readonly string Review = "~/Areas/Admin/Views/Import/Review.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_ImportController: Ascend.Web.Areas.Admin.Controllers.ImportController {
        public T4MVC_ImportController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(Ascend.Web.Areas.Admin.Controllers.ImportCreateModel i) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("i", i);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id, Ascend.Web.Areas.Admin.Controllers.ImportEditModel i, bool import) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("i", i);
            callInfo.RouteValues.Add("import", import);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Review() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Review);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Events() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Events);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Events(System.Web.Mvc.FormCollection form) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Events);
            callInfo.RouteValues.Add("form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Reset() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Reset);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Reset(bool confirm) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Reset);
            callInfo.RouteValues.Add("confirm", confirm);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Randomizer() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Randomizer);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Randomizer(Ascend.Web.Areas.Admin.Controllers.RandomizerModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Randomizer);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
