// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Admin.Controllers {
    [CompilerGenerated]
    public partial class MessagingController {
        public MessagingController() { }

        protected MessagingController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Messages() {
            return new T4MVC_ActionResult(Area, Name, Actions.Messages);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Display() {
            return new T4MVC_ActionResult(Area, Name, Actions.Display);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Resend() {
            return new T4MVC_ActionResult(Area, Name, Actions.Resend);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, Actions.Edit);
        }

        public readonly string Area = "Admin";
        public readonly string Name = "Messaging";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Messages = "Messages";
            public readonly string Activation = "Activation";
            public readonly string Welcome = "Welcome";
            public readonly string Display = "Display";
            public readonly string Resend = "Resend";
            public readonly string Edit = "Edit";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Activation = "~/Areas/Admin/Views/Messaging/Activation.spark";
            public readonly string Display = "~/Areas/Admin/Views/Messaging/Display.spark";
            public readonly string Edit = "~/Areas/Admin/Views/Messaging/Edit.spark";
            public readonly string Index = "~/Areas/Admin/Views/Messaging/Index.spark";
            public readonly string Messages = "~/Areas/Admin/Views/Messaging/Messages.spark";
            public readonly string TemplateCreateModel = "~/Areas/Admin/Views/Messaging/TemplateCreateModel.spark";
            public readonly string Welcome = "~/Areas/Admin/Views/Messaging/Welcome.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_MessagingController: Ascend.Web.Areas.Admin.Controllers.MessagingController {
        public T4MVC_MessagingController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(Ascend.Web.Areas.Admin.Controllers.TemplateCreateModel t) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("t", t);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Messages(int? last, string address) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Messages);
            callInfo.RouteValues.Add("last", last);
            callInfo.RouteValues.Add("address", address);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Activation() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Activation);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Activation(string[] id, bool send) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Activation);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("send", send);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Welcome() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Welcome);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Welcome(string[] id, bool send) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Welcome);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("send", send);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Display(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Display);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Resend(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Resend);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id, Ascend.Web.Areas.Admin.Controllers.TemplateEditModel t) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Edit);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("t", t);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
