// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin {
    [CompilerGenerated]
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string _Navigation = "~/Areas/Admin/Views/Shared/_Navigation.spark";
            public readonly string Application = "~/Areas/Admin/Views/Shared/Application.spark";
            public readonly string FileChooser = "~/Areas/Admin/Views/Shared/FileChooser.spark";
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string AccountChooser = "~/Areas/Admin/Views/Shared/EditorTemplates/AccountChooser.spark";
                public readonly string AvailabilityEditModel = "~/Areas/Admin/Views/Shared/EditorTemplates/AvailabilityEditModel.spark";
                public readonly string BudgetEditModel = "~/Areas/Admin/Views/Shared/EditorTemplates/BudgetEditModel.spark";
                public readonly string ContentEditModel = "~/Areas/Admin/Views/Shared/EditorTemplates/ContentEditModel.spark";
                public readonly string FolderEditModel = "~/Areas/Admin/Views/Shared/EditorTemplates/FolderEditModel.spark";
                public readonly string GroupChooser = "~/Areas/Admin/Views/Shared/EditorTemplates/GroupChooser.spark";
                public readonly string GroupMultiChooser = "~/Areas/Admin/Views/Shared/EditorTemplates/GroupMultiChooser.spark";
                public readonly string IssuanceEditModel = "~/Areas/Admin/Views/Shared/EditorTemplates/IssuanceEditModel.spark";
                public readonly string Ledger = "~/Areas/Admin/Views/Shared/EditorTemplates/Ledger.spark";
                public readonly string UserChooser = "~/Areas/Admin/Views/Shared/EditorTemplates/UserChooser.spark";
                public readonly string UserMultiChooser = "~/Areas/Admin/Views/Shared/EditorTemplates/UserMultiChooser.spark";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
