// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Dash.Controllers {
    [CompilerGenerated]
    public partial class WidgetController {
        public WidgetController() { }

        protected WidgetController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult TimelineControlAccount() {
            return new T4MVC_ActionResult(Area, Name, Actions.TimelineControlAccount);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult TimelineExpenseAccount() {
            return new T4MVC_ActionResult(Area, Name, Actions.TimelineExpenseAccount);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult TimelineLiability() {
            return new T4MVC_ActionResult(Area, Name, Actions.TimelineLiability);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult PercentLoginsThisWeek() {
            return new T4MVC_ActionResult(Area, Name, Actions.PercentLoginsThisWeek);
        }

        public readonly string Area = "Dash";
        public readonly string Name = "Widget";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string TimelineControlAccount = "TimelineControlAccount";
            public readonly string TimelineExpenseAccount = "TimelineExpenseAccount";
            public readonly string TimelineLiability = "TimelineLiability";
            public readonly string PercentLoginsThisWeek = "PercentLoginsThisWeek";
            public readonly string PercentLoginsThisMonth = "PercentLoginsThisMonth";
            public readonly string Org = "Org";
            public readonly string BudgetSpend = "BudgetSpend";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
        }
    }

    [CompilerGenerated]
    class T4MVC_WidgetController: Ascend.Web.Areas.Dash.Controllers.WidgetController {
        public T4MVC_WidgetController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult TimelineControlAccount(System.Web.Mvc.FormCollection form) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.TimelineControlAccount);
            callInfo.RouteValues.Add("form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TimelineExpenseAccount(System.Web.Mvc.FormCollection form) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.TimelineExpenseAccount);
            callInfo.RouteValues.Add("form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TimelineLiability(System.Web.Mvc.FormCollection form) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.TimelineLiability);
            callInfo.RouteValues.Add("form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PercentLoginsThisWeek(System.Web.Mvc.FormCollection form) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.PercentLoginsThisWeek);
            callInfo.RouteValues.Add("form", form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PercentLoginsThisMonth() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.PercentLoginsThisMonth);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Org() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Org);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BudgetSpend() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.BudgetSpend);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
