// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Mobile.Controllers {
    [CompilerGenerated]
    public partial class HomeController {
        public HomeController() { }

        protected HomeController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Product() {
            return new T4MVC_ActionResult(Area, Name, Actions.Product);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Distribute() {
            return new T4MVC_ActionResult(Area, Name, Actions.Distribute);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Award() {
            return new T4MVC_ActionResult(Area, Name, Actions.Award);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult RewardCode() {
            return new T4MVC_ActionResult(Area, Name, Actions.RewardCode);
        }

        public readonly string Area = "Mobile";
        public readonly string Name = "Home";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Wishlist = "Wishlist";
            public readonly string Product = "Product";
            public readonly string Budget = "Budget";
            public readonly string Distribute = "Distribute";
            public readonly string Award = "Award";
            public readonly string RewardCode = "RewardCode";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Award = "~/Areas/Mobile/Views/Home/Award.spark";
            public readonly string Budget = "~/Areas/Mobile/Views/Home/Budget.spark";
            public readonly string Distribute = "~/Areas/Mobile/Views/Home/Distribute.spark";
            public readonly string Index = "~/Areas/Mobile/Views/Home/Index.spark";
            public readonly string Product = "~/Areas/Mobile/Views/Home/Product.spark";
            public readonly string Wishlist = "~/Areas/Mobile/Views/Home/Wishlist.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_HomeController: Ascend.Web.Areas.Mobile.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Wishlist() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Wishlist);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Product(string userId, string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Product);
            callInfo.RouteValues.Add("userId", userId);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Budget() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Budget);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Distribute(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Distribute);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Distribute(string id, Ascend.Web.Areas.Site.Controllers.BudgetDistributionModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Distribute);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Award(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Award);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Award(string id, Ascend.Web.Areas.Site.Controllers.UserAwardViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Award);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RewardCode(string rewardcode) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.RewardCode);
            callInfo.RouteValues.Add("rewardcode", rewardcode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
