// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Public.Controllers {
    [CompilerGenerated]
    public partial class LoginController {
        public LoginController() { }

        protected LoginController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Page() {
            return new T4MVC_ActionResult(Area, Name, Actions.Page);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Find() {
            return new T4MVC_ActionResult(Area, Name, Actions.Find);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Activate() {
            return new T4MVC_ActionResult(Area, Name, Actions.Activate);
        }

        public readonly string Area = "Public";
        public readonly string Name = "Login";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Page = "Page";
            public readonly string Find = "Find";
            public readonly string Index = "Index";
            public readonly string Logout = "Logout";
            public readonly string Register = "Register";
            public readonly string Activate = "Activate";
            public readonly string Reset = "Reset";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Index = "~/Areas/Public/Views/Login/Index.spark";
            public readonly string Maintenance = "~/Areas/Public/Views/Login/Maintenance.spark";
            public readonly string NoDomain = "~/Areas/Public/Views/Login/NoDomain.spark";
            public readonly string Register = "~/Areas/Public/Views/Login/Register.spark";
            public readonly string Reset = "~/Areas/Public/Views/Login/Reset.spark";
            public readonly string ResetSuccess = "~/Areas/Public/Views/Login/ResetSuccess.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_LoginController: Ascend.Web.Areas.Public.Controllers.LoginController {
        public T4MVC_LoginController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Page(string page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Page);
            callInfo.RouteValues.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Find(string e) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Find);
            callInfo.RouteValues.Add("e", e);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string login, string password) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("login", login);
            callInfo.RouteValues.Add("password", password);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Logout() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Logout);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Register);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Activate(string code) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Activate);
            callInfo.RouteValues.Add("code", code);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Reset() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Reset);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Reset(Ascend.Web.Areas.Public.Controllers.PasswordResetViewModel reset) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Reset);
            callInfo.RouteValues.Add("reset", reset);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
