// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    [CompilerGenerated]
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string _Analytics = "~/Views/Shared/_Analytics.spark";
            public readonly string _Notifications = "~/Views/Shared/_Notifications.spark";
            public readonly string _Topbar = "~/Views/Shared/_Topbar.spark";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string Address = "~/Views/Shared/DisplayTemplates/Address.spark";
                public readonly string ContentViewModel = "~/Views/Shared/DisplayTemplates/ContentViewModel.spark";
                public readonly string DateTime = "~/Views/Shared/DisplayTemplates/DateTime.spark";
                public readonly string Phone = "~/Views/Shared/DisplayTemplates/Phone.spark";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string Address = "~/Views/Shared/EditorTemplates/Address.spark";
                public readonly string Availability = "~/Views/Shared/EditorTemplates/Availability.spark";
                public readonly string DateTime = "~/Views/Shared/EditorTemplates/DateTime.spark";
                public readonly string Enum = "~/Views/Shared/EditorTemplates/Enum.spark";
                public readonly string Phone = "~/Views/Shared/EditorTemplates/Phone.spark";
                public readonly string TextArea = "~/Views/Shared/EditorTemplates/TextArea.spark";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
