// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Site.Controllers {
    [CompilerGenerated]
    public partial class CartController {
        public CartController() { }

        protected CartController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Update() {
            return new T4MVC_ActionResult(Area, Name, Actions.Update);
        }

        public readonly string Area = "Site";
        public readonly string Name = "Cart";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Wishlist = "Wishlist";
            public readonly string Update = "Update";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Empty = "~/Areas/Site/Views/Cart/Empty.spark";
            public readonly string Index = "~/Areas/Site/Views/Cart/Index.spark";
            public readonly string Wishlist = "~/Areas/Site/Views/Cart/Wishlist.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_CartController: Ascend.Web.Areas.Site.Controllers.CartController {
        public T4MVC_CartController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string productId, string optionName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("productId", productId);
            callInfo.RouteValues.Add("optionName", optionName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Wishlist() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Wishlist);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Update(string type, string productId, string optionName, int? quantity) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Update);
            callInfo.RouteValues.Add("type", type);
            callInfo.RouteValues.Add("productId", productId);
            callInfo.RouteValues.Add("optionName", optionName);
            callInfo.RouteValues.Add("quantity", quantity);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
