// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Site {
    [CompilerGenerated]
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string _FlatMenu = "~/Areas/Site/Views/Shared/_FlatMenu.spark";
            public readonly string _Menu = "~/Areas/Site/Views/Shared/_Menu.spark";
            public readonly string Application = "~/Areas/Site/Views/Shared/Application.spark";
            public readonly string Unavailable = "~/Areas/Site/Views/Shared/Unavailable.spark";
            static readonly _Modules s_Modules = new _Modules();
            public _Modules Modules { get { return s_Modules; } }
            public partial class _Modules{
                public readonly string Balance = "~/Areas/Site/Views/Shared/Modules/Balance.spark";
                public readonly string Budget = "~/Areas/Site/Views/Shared/Modules/Budget.spark";
                public readonly string Cart = "~/Areas/Site/Views/Shared/Modules/Cart.spark";
                public readonly string Wishlist = "~/Areas/Site/Views/Shared/Modules/Wishlist.spark";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
