// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Site.Controllers {
    [CompilerGenerated]
    public partial class QuizController {
        public QuizController() { }

        protected QuizController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, Actions.Index);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Review() {
            return new T4MVC_ActionResult(Area, Name, Actions.Review);
        }

        public readonly string Area = "Site";
        public readonly string Name = "Quiz";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Review = "Review";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Index = "~/Areas/Site/Views/Quiz/Index.spark";
            public readonly string Review = "~/Areas/Site/Views/Quiz/Review.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_QuizController: Ascend.Web.Areas.Site.Controllers.QuizController {
        public T4MVC_QuizController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string id, Ascend.Web.Areas.Site.Controllers.QuizResultViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Review(string id, string r) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Review);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("r", r);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
