// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable 0108
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Ascend.Web.Areas.Site.Controllers {
    [CompilerGenerated]
    public partial class AwardController {
        public AwardController() { }

        protected AwardController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, Actions.Index);
        }
        [NonAction]
        public System.Web.Mvc.JsonResult Search() {
            return new T4MVC_JsonResult(Area, Name, Actions.Search);
        }

        public readonly string Area = "Site";
        public readonly string Name = "Award";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string Index = "Index";
            public readonly string Search = "Search";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string Index = "~/Areas/Site/Views/Award/Index.spark";
        }
    }

    [CompilerGenerated]
    class T4MVC_AwardController: Ascend.Web.Areas.Site.Controllers.AwardController {
        public T4MVC_AwardController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string id, Ascend.Web.Areas.Site.Controllers.UserAwardViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Index);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Search(string id, string q) {
            var callInfo = new T4MVC_JsonResult(Area, Name, Actions.Search);
            callInfo.RouteValues.Add("id", id);
            callInfo.RouteValues.Add("q", q);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
#pragma warning restore 0108
